### ISSUE TITLE
Thank YOU!! 

### ISSUE THREAD

**Issue by TonyTromp** [fwestenberg/homeassistant-devialet#4]
I almost coded this one up until i stumbled into your git repo. This is way better and much more complete than the features i was planning to implement. Many thanks for saving me the effort and enjoying your fantastic Hass intergration.

Please add a 'buy me a coffee' or paypal link to your Readme, so we can at least get you some good morning beans! 

Werkt perfect met mijn Phantom 2 set.
Bedankt man!

Groeten,
Tony

**Comment by fwestenberg** [comment]
Hi Tony,

Thanks for your message! Glad to hear someone is enjoying it, please let me know if you find some issue. 
If you want to do me/us a favour, please review this PR for the official integration:

https://github.com/home-assistant/core/pull/86551
