### ISSUE TITLE
Issue with adding devices: Config flow could not be loaded

### ISSUE THREAD

**Issue by SnippetSpace** [fwestenberg/homeassistant-devialet#5]
Hey, thank you so much for building this.
I am not very experienced with home assistant. Have added the custom repository and restarted the app.
When trying to find the devialet's from the devices menu i get this error:

"Config flow could not be loaded: {"message":"Invalid handler specified"}"

Any idea what this can mean? Probably an issue with my setup.
![step 1](https://github.com/fwestenberg/homeassistant-devialet/assets/917744/2bc84025-b1d1-4588-932e-2ff56bf24fd1)
![step 2](https://github.com/fwestenberg/homeassistant-devialet/assets/917744/4e329b2a-1ed2-4698-884d-c7ef2b92d024)

**Comment by fwestenberg** [comment]
Did you solve this already? If not, please attach more information from the logging please.

**Comment by SnippetSpace** [comment]
Hello yes this is still an issue even after reinstalling home assistant. Not sure how to get detailled logs but this is the response in the container log: 
`ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration devialet: No module named 'devialet'`

However I did copy the "devialet" folder into the custom components folder (same level as HACS) so it should exist?

**Comment by SnippetSpace** [comment]
hm nevermind after another few restarts of home assistant it somehow started working1
